name: ðŸš€ Deploy
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
      - next_release/*
      - release/*

jobs:
  build-and-publish:
    uses: openmsa/openmsa-gha/.github/workflows/normal-build.yaml@master
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      REPO_ACCESS_TOKEN: ${{ secrets.MSA_DOCKER_REPO_ACCESS_TOKEN  }}
    with:
      container-name: ubiqube/msa2-adapters

